In [1]:
import pandas as pd 
import numpy as np 
import pickle

with open("master_database.pkl", "rb") as f:
    df = pickle.load(f)

df

,room_type_id,room_type_name,forecast_date,forecasted_price,high_season_positive_multiplier_rate,all_season_positive_multiplier_rate,high_season_negative_multiplier_rate,all_season_negative_multiplier_rate,all_room_types_min_forecasted_price,all_room_types_median_forecasted_price,all_room_types_max_forecasted_price,flag,customer_id,currency_id,_source
0,177,Comfort Budget Twin Room,2026-05-02,179572.58,0.0,0.00,0.0,0.0,None,None,None,1.0,3.0,1.0,0
1,178,Comfort Budget Double Room,2026-05-02,165343.00,0.0,0.00,0.0,0.0,None,None,None,1.0,3.0,1.0,0
2,135,One OR Two Bedroom Private Pool Villa,2026-05-02,1104295.70,0.0,0.03,0.0,0.0,None,None,None,1.0,6.0,1.0,0
3,133,Three Bedroom Private Pool Villa,2026-05-02,1180549.50,0.0,0.00,0.0,0.0,None,None,None,1.0,6.0,1.0,0
4,134,Three Bedroom Private Pool Villa Two Story,2026-05-02,1634374.00,0.0,0.00,0.0,0.0,None,None,None,1.0,6.0,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10215,223,Deluxe Room,2026-04-29,624382.00,0.0,0.00,0.0,0.0,None,None,None,4.0,2.0,1.0,0
10216,223,Deluxe Room,2026-04-30,624382.00,0.0,0.00,0.0,0.0,None,None,None,4.0,2.0,1.0,0
10217,223,Deluxe Room,2026-05-01,624382.00,0.0,0.00,0.0,0.0,None,None,None,4.0,2.0,1.0,0
10218,223,Deluxe Room,2026-05-02,624382.00,0.0,0.00,0.0,0.0,None,None,None,4.0,2.0,1.0,0
10219,223,Deluxe Room,2026-05-03,624382.00,0.0,0.00,0.0,0.0,None,None,None,4.0,2.0,1.0,0

In [2]:
df[df["flag"] == 2.0].head(40)

,room_type_id,room_type_name,forecast_date,forecasted_price,high_season_positive_multiplier_rate,all_season_positive_multiplier_rate,high_season_negative_multiplier_rate,all_season_negative_multiplier_rate,all_room_types_min_forecasted_price,all_room_types_median_forecasted_price,all_room_types_max_forecasted_price,flag,customer_id,currency_id,_source
7596,177,Comfort Budget Twin Room,2026-04-02,175436.00,0.0,0.0,0.0,0.0,None,None,None,2.0,3.0,1.0,0
7597,178,Comfort Budget Double Room,2026-04-02,165332.00,0.0,0.0,0.0,0.0,None,None,None,2.0,3.0,1.0,0
7598,223,Deluxe Room,2026-04-02,628576.75,0.0,0.0,0.0,0.0,None,None,None,2.0,2.0,1.0,0
7599,135,One OR Two Bedroom Private Pool Villa,2026-04-02,1068947.00,0.0,0.0,0.0,0.0,,,,2.0,6.0,1.0,0
7600,133,Three Bedroom Private Pool Villa,2026-04-02,1171555.00,0.0,0.0,0.0,0.0,None,None,None,2.0,6.0,1.0,0
7601,134,Three Bedroom Private Pool Villa Two Story,2026-04-02,1482921.00,0.0,0.0,0.0,0.0,None,None,None,2.0,6.0,1.0,0
7602,487,Deluxe Room Mountain and Pool View,2026-04-02,387488.00,0.0,0.0,0.0,0.0,,,,2.0,10.0,1.0,0
7603,488,Deluxe Signature Room,2026-04-02,508570.00,0.0,0.0,0.0,0.0,None,None,None,2.0,10.0,1.0,0
7604,284,Blanjong Room,2026-04-02,192703.00,0.0,0.0,0.0,0.0,,,,2.0,7.0,1.0,0
7605,285,Suite Room,2026-04-02,241301.00,0.0,0.0,0.0,0.0,,,,2.0,7.0,1.0,0
7606,187,Standard Villa,2026-04-02,666706.00,0.0,0.0,0.0,0.0,,,,2.0,9.0,1.0,0
7607,189,Onebedroom Deluxe with Mountain View,2026-04-02,800000.00,0.0,0.0,0.0,0.0,None,None,None,2.0,9.0,1.0,0
7608,188,Onebedroom Deluxe with Pool View,2026-04-02,766711.00,0.0,0.0,0.0,0.0,None,None,None,2.0,9.0,1.0,0
7609,190,Two Bedrooom Mountain View,2026-04-02,1222327.00,0.0,0.0,0.0,0.0,None,None,None,2.0,9.0,1.0,0
7610,191,Deluxe Two Bedroom Mountain View,2026-04-02,1360975.00,0.0,0.0,0.0,0.0,None,None,None,2.0,9.0,1.0,0
7611,338,Deluxe Room,2026-04-02,126548.00,0.0,0.0,0.0,0.0,,,,2.0,11.0,1.0,0
7612,338,Deluxe Room,2026-04-03,130056.00,0.0,0.0,0.0,0.0,,,,2.0,11.0,1.0,0
7613,338,Deluxe Room,2026-04-04,127247.00,0.0,0.0,0.0,0.0,,,,2.0,11.0,1.0,0
7614,338,Deluxe Room,2026-04-05,135361.00,0.0,0.0,0.0,0.0,,,,2.0,11.0,1.0,0
7615,338,Deluxe Room,2026-04-06,125367.00,0.0,0.0,0.0,0.0,,,,2.0,11.0,1.0,0
7616,338,Deluxe Room,2026-04-07,125507.00,0.0,0.0,0.0,0.0,,,,2.0,11.0,1.0,0
7617,338,Deluxe Room,2026-04-08,126156.00,0.0,0.0,0.0,0.0,,,,2.0,11.0,1.0,0
7618,338,Deluxe Room,2026-04-09,126548.00,0.0,0.0,0.0,0.0,,,,2.0,11.0,1.0,0
7619,338,Deluxe Room,2026-04-10,126884.00,0.0,0.0,0.0,0.0,,,,2.0,11.0,1.0,0
7620,338,Deluxe Room,2026-04-11,127247.00,0.0,0.0,0.0,0.0,,,,2.0,11.0,1.0,0
7621,338,Deluxe Room,2026-04-12,132059.00,0.0,0.0,0.0,0.0,,,,2.0,11.0,1.0,0
7622,338,Deluxe Room,2026-04-13,126512.00,0.0,0.0,0.0,0.0,,,,2.0,11.0,1.0,0
7623,338,Deluxe Room,2026-04-14,126653.00,0.0,0.0,0.0,0.0,,,,2.0,11.0,1.0,0
7624,338,Deluxe Room,2026-04-15,127308.00,0.0,0.0,0.0,0.0,,,,2.0,11.0,1.0,0
7625,338,Deluxe Room,2026-04-16,127704.00,0.0,0.0,0.0,0.0,,,,2.0,11.0,1.0,0
7626,338,Deluxe Room,2026-04-17,128043.00,0.0,0.0,0.0,0.0,,,,2.0,11.0,1.0,0
7627,338,Deluxe Room,2026-04-18,128410.00,0.0,0.0,0.0,0.0,,,,2.0,11.0,1.0,0
7628,338,Deluxe Room,2026-04-19,133266.00,0.0,0.0,0.0,0.0,,,,2.0,11.0,1.0,0
7629,338,Deluxe Room,2026-04-20,114458.00,0.0,0.0,0.0,0.0,,,,2.0,11.0,1.0,0
7630,338,Deluxe Room,2026-04-21,114586.00,0.0,0.0,0.0,0.0,,,,2.0,11.0,1.0,0
7631,338,Deluxe Room,2026-04-22,115179.00,0.0,0.0,0.0,0.0,,,,2.0,11.0,1.0,0
7632,338,Deluxe Room,2026-04-23,115537.00,0.0,0.0,0.0,0.0,,,,2.0,11.0,1.0,0
7633,338,Deluxe Room,2026-04-24,115843.00,0.0,0.0,0.0,0.0,,,,2.0,11.0,1.0,0
7634,338,Deluxe Room,2026-04-25,116175.00,0.0,0.0,0.0,0.0,,,,2.0,11.0,1.0,0
7635,338,Deluxe Room,2026-04-26,120568.00,0.0,0.0,0.0,0.0,,,,2.0,11.0,1.0,0

In [7]:
presentation_charts = {
    "model_version": "v1.0.0",
    "customer_id": "",
    "currency_id": "",
    "forecasts": []
}

counter = 0
for i in df["customer_id"].unique():
    if counter > 3 : break 
    
    highlight_df = df[df["customer_id"] == i]
    highlight_df["room_type_id"] = highlight_df["room_type_id"].astype(int)
    highlight_df = highlight_df.sort_values("room_type_id", ascending=True)

    id_storage = i
    curr_id_storage = highlight_df["currency_id"].iloc[0]

    highlight_df = highlight_df.drop(columns=["customer_id", "currency_id", "flag", "_source"])
    presentation_charts_copy = presentation_charts.copy()
    interest_json = highlight_df.to_dict(orient="records")
    presentation_charts_copy["customer_id"] = id_storage
    presentation_charts_copy["currency_id"] = curr_id_storage
    sep_box = []
    inner_counter = 0
    for ii in range(len(interest_json)):
        if inner_counter > 3: break
        print(interest_json[ii])
        sep_box.append(interest_json[ii])
        inner_counter += 1
    presentation_charts_copy["forecasts"] = sep_box
    print(presentation_charts_copy["forecasts"])
    counter += 1

{'room_type_id': 177, 'room_type_name': 'Comfort Budget Twin Room', 'forecast_date': '2026-05-02', 'forecasted_price': 179572.58, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': 0.0, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}
{'room_type_id': 177, 'room_type_name': 'Comfort Budget Twin Room', 'forecast_date': '2026-05-16', 'forecasted_price': 178752.77, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': 0.0, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}
{'room_type_id': 177, 'room_type_name': 'Comfort Budget Twin Room', 'forecast_date': '2026-05-17', 'forecasted_price': 178752.77, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': 0.0, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}
{'room_type_id': 177, 'room_type_name': 'Comfort Budget Twin Room', 'forecast_date': '2026-05-18', 'forecasted_price': 178752.77, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': 0.0, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}
[{'room_type_id': 177, 'room_type_name': 'Comfort Budget Twin Room', 'forecast_date': '2026-05-02', 'forecasted_price': 179572.58, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': 0.0, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}, {'room_type_id': 177, 'room_type_name': 'Comfort Budget Twin Room', 'forecast_date': '2026-05-16', 'forecasted_price': 178752.77, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': 0.0, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}, {'room_type_id': 177, 'room_type_name': 'Comfort Budget Twin Room', 'forecast_date': '2026-05-17', 'forecasted_price': 178752.77, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': 0.0, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}, {'room_type_id': 177, 'room_type_name': 'Comfort Budget Twin Room', 'forecast_date': '2026-05-18', 'forecasted_price': 178752.77, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': 0.0, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}]
{'room_type_id': 133, 'room_type_name': 'Three Bedroom Private Pool Villa', 'forecast_date': '2026-08-19', 'forecasted_price': 1183544.0, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': 0.0, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}
{'room_type_id': 133, 'room_type_name': 'Three Bedroom Private Pool Villa', 'forecast_date': '2026-08-18', 'forecasted_price': 1183544.0, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': 0.0, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}
{'room_type_id': 133, 'room_type_name': 'Three Bedroom Private Pool Villa', 'forecast_date': '2026-08-17', 'forecasted_price': 1183544.0, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': 0.0, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}
{'room_type_id': 133, 'room_type_name': 'Three Bedroom Private Pool Villa', 'forecast_date': '2026-08-16', 'forecasted_price': 1183544.0, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': 0.0, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}
[{'room_type_id': 133, 'room_type_name': 'Three Bedroom Private Pool Villa', 'forecast_date': '2026-08-19', 'forecasted_price': 1183544.0, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': 0.0, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}, {'room_type_id': 133, 'room_type_name': 'Three Bedroom Private Pool Villa', 'forecast_date': '2026-08-18', 'forecasted_price': 1183544.0, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': 0.0, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}, {'room_type_id': 133, 'room_type_name': 'Three Bedroom Private Pool Villa', 'forecast_date': '2026-08-17', 'forecasted_price': 1183544.0, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': 0.0, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}, {'room_type_id': 133, 'room_type_name': 'Three Bedroom Private Pool Villa', 'forecast_date': '2026-08-16', 'forecasted_price': 1183544.0, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': 0.0, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}]
{'room_type_id': 284, 'room_type_name': 'Blanjong Room', 'forecast_date': '2026-05-09', 'forecasted_price': 206646.75, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': -0.01, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}
{'room_type_id': 284, 'room_type_name': 'Blanjong Room', 'forecast_date': '2026-05-08', 'forecasted_price': 219624.3, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': -0.01, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}
{'room_type_id': 284, 'room_type_name': 'Blanjong Room', 'forecast_date': '2026-05-07', 'forecasted_price': 219624.3, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': -0.01, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}
{'room_type_id': 284, 'room_type_name': 'Blanjong Room', 'forecast_date': '2026-05-06', 'forecasted_price': 219624.3, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': -0.01, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}
[{'room_type_id': 284, 'room_type_name': 'Blanjong Room', 'forecast_date': '2026-05-09', 'forecasted_price': 206646.75, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': -0.01, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}, {'room_type_id': 284, 'room_type_name': 'Blanjong Room', 'forecast_date': '2026-05-08', 'forecasted_price': 219624.3, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': -0.01, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}, {'room_type_id': 284, 'room_type_name': 'Blanjong Room', 'forecast_date': '2026-05-07', 'forecasted_price': 219624.3, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': -0.01, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}, {'room_type_id': 284, 'room_type_name': 'Blanjong Room', 'forecast_date': '2026-05-06', 'forecasted_price': 219624.3, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': -0.01, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}]
{'room_type_id': 223, 'room_type_name': 'Deluxe Room', 'forecast_date': '2026-05-02', 'forecasted_price': 633449.62, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': 0.0, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}
{'room_type_id': 223, 'room_type_name': 'Deluxe Room', 'forecast_date': '2026-04-02', 'forecasted_price': 628576.75, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': 0.0, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}
{'room_type_id': 223, 'room_type_name': 'Deluxe Room', 'forecast_date': '2026-05-03', 'forecasted_price': 655283.59, 'high_season_positive_multiplier_rate': 0.04, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': 0.0, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}
{'room_type_id': 223, 'room_type_name': 'Deluxe Room', 'forecast_date': '2026-05-04', 'forecasted_price': 648982.79, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.03, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': 0.0, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}
[{'room_type_id': 223, 'room_type_name': 'Deluxe Room', 'forecast_date': '2026-05-02', 'forecasted_price': 633449.62, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': 0.0, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}, {'room_type_id': 223, 'room_type_name': 'Deluxe Room', 'forecast_date': '2026-04-02', 'forecasted_price': 628576.75, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': 0.0, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}, {'room_type_id': 223, 'room_type_name': 'Deluxe Room', 'forecast_date': '2026-05-03', 'forecasted_price': 655283.59, 'high_season_positive_multiplier_rate': 0.04, 'all_season_positive_multiplier_rate': 0.0, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': 0.0, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}, {'room_type_id': 223, 'room_type_name': 'Deluxe Room', 'forecast_date': '2026-05-04', 'forecasted_price': 648982.79, 'high_season_positive_multiplier_rate': 0.0, 'all_season_positive_multiplier_rate': 0.03, 'high_season_negative_multiplier_rate': 0.0, 'all_season_negative_multiplier_rate': 0.0, 'all_room_types_min_forecasted_price': None, 'all_room_types_median_forecasted_price': None, 'all_room_types_max_forecasted_price': None}]

/tmp/ipykernel_3757/4070264314.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  highlight_df["room_type_id"] = highlight_df["room_type_id"].astype(int)
/tmp/ipykernel_3757/4070264314.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  highlight_df["room_type_id"] = highlight_df["room_type_id"].astype(int)
/tmp/ipykernel_3757/4070264314.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  highlight_df["room_type_id"] = highlight_df["room_type_id"].astype(int)
/tmp/ipykernel_3757/4070264314.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  highlight_df["room_type_id"] = highlight_df["room_type_id"].astype(int)